version: '3.8'

services:
  citydrive-db:
    image: postgres:15
    container_name: citydrive-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: citydrivedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Atestat_1
    volumes:
      - citydrive-pgdata:/var/lib/postgresql/data

volumes:
  citydrive-pgdata:
